Remake api.js
ilyasidorchik/sdamgia-introtask-ruslan pull request #10
Opened 2020-11-12 11:27 UTC by akseonowww

2020-11-12 11:36 UTC, ilyasidorchik requested changes

2020-11-12 11:36 UTC, ilyasidorchik commented on src/components/Search/api.js
> +const getSomething = async (value) => {
Нужно поменять название и сделать именованный экспорт.

2020-11-12 11:36 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +  const SearchForm = () => {
Лучше назвать `useHelpers`, потому что это хук, а не компонент. И вынести.

2020-11-12 13:19 UTC, ilyasidorchik requested changes

2020-11-12 13:19 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +  const useHelpers = () => {
Да, но внутри этого хука лучше сначала определить функции, а потом экспортнуть. И сам хук вынести в папку `hooks`.

2020-11-12 13:19 UTC, ilyasidorchik commented on src/components/Search/api.js
> +export const getApi = async (value) => {
О названии. Представь, у тебя большое приложение, куча запросов, и они все будут называться `getApi`? Лучше написать конкретное, например если нужен баланс карты, то `getCardBalance`.

2020-11-12 13:37 UTC, ilyasidorchik requested changes

2020-11-12 13:37 UTC, ilyasidorchik commented on src/components/Search/Search.js
>  const Search = () => {
Теперь добавь сюда хелперы

2020-11-13 07:16 UTC, akseonowww commented on src/components/Search/Search.js
> +  const useHelpers = () => {
> определить функции
Записать в виде стрелочной функции?

2020-11-13 07:21 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +  const useHelpers = () => {
Имею в виду следующее:
Ты сначала пишешь `const handleSmth = () => {}`, а потом экспортируешь.

2020-11-13 13:26 UTC, ilyasidorchik requested changes

2020-11-13 13:26 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +import { handleChange, handleSubmit } from './hooks/useHelper'
Ты должен импортировать хук: можно разделить на `useHandleChange` и `useHandleSubmit`, но давай в нашем случае `useHelpers`. Кстати, обрати внимание, что ты пропустил `s` в названии файла.

2020-11-13 13:26 UTC, ilyasidorchik commented on src/components/Search/Search.js
> -  const { handleChange, handleSubmit } = useHelpers()
То есть эта строка останется.

2020-11-13 14:02 UTC, ilyasidorchik requested changes

2020-11-13 14:02 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +import useHelpers from './hooks/useHelpers'
Представь, что у тебя будет много хуков. Поэтому лучше именованный экспорт.

2020-11-13 14:58 UTC, ilyasidorchik requested changes

2020-11-13 14:58 UTC, ilyasidorchik commented on src/components/Search/hooks/useHelpers.js
> +export const handleChange = () => {
Они должны быть экспортированы из хука.

2020-11-14 10:00 UTC, ilyasidorchik requested changes
В целом, ок. Почти всё готово.

2020-11-14 10:00 UTC, ilyasidorchik commented on src/components/Search/Search.js
>    const cnSearch = cn("Search")
Лучше поставить её в самом начале компонента.

2020-11-14 10:00 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +import { useHelpers } from './hooks/useHelpers'
Представь, что у тебя будет куча хуков в реальном проекте. Ты же не будешь импортировать так на много строк? Как можно упростить импорт?
```
import { useData } from './hooks/useData'
import { useHelpers } from './hooks/useHelpers'
import { useFetchData } from './hooks/useFetchData'
import { useActions } from './hooks/useActions'
import { useOptions } from './hooks/useOptions'
```

2020-11-14 10:33 UTC, akseonowww commented on src/components/Search/Search.js
> +import { useHelpers } from './hooks/useHelpers'
```
import * as allHooks from './hooks/allHooks'
const useHelpers = () => { return allHooks.useHelpers }
```

2020-11-15 14:47 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +import { useHelpers } from './hooks/useHelpers'
Да, как вариант. Но так ты повторяешь `allHooks`. Хочется вот так:
```js
import { useData, useSuperPuper } from './hooks'
```


Для этого нужно сделать в директории `hooks` индексовый файл:
```js
export * from './useData'
export * from './useSuperPuper'
```

2020-11-15 15:56 UTC, ilyasidorchik requested changes
Ты запускаешь приложение перед тем, как отправить на ревью?

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/53493445/99189796-1d86df80-2774-11eb-8b07-d8b2f9955155.png">

2020-11-15 16:15 UTC, akseonowww commented
Да, запускаю. Думал так всё и должно быть, то есть потом будет задача всё исправить. 
Я просто не понимаю как можно функции вида useState перекидывать в хук.

2020-11-15 16:37 UTC, ilyasidorchik commented
Приложение должно работать перед отправкой на ревью. Нужно убирать все ошибки и, желательно, предупреждения.


> как можно функции вида useState перекидывать в хук.

В начале мы учили с тобой типы данных, на них всё строится. Хук — это обычная функция, а результат `useState`, переменные `value` и `setValue`,— это строка и функция, соответственно. Ты можешь передать в функцию строку и функцию, значит, можешь передать в хук.

2020-11-15 16:45 UTC, akseonowww commented
Понял. А что делть с ошибкой useCallback?
`React Hook "useCallback" is called in function "handleChange" which is neither a React function component or a custom React Hook function  react-hooks/rules-of-hooks`

2020-11-15 17:49 UTC, ilyasidorchik commented
Ты неправильно сделал эти функции-хелперы. Ты возвращаешь сам юз-колбек, а нужно его применить.

2020-11-15 18:39 UTC, ilyasidorchik requested changes

2020-11-15 18:39 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +  const { handleChange, handleSubmit } = useHelpers(value, setValue, setResult)
Супер. Но ты используешь в файле `Search` функцию `setValue`? Что, если вынести этот стейт в хук?

2020-11-16 20:36 UTC, ilyasidorchik requested changes

2020-11-16 20:36 UTC, ilyasidorchik commented on src/components/Search/api.js
> +export const getApi = async (value) => {
Кстати. Хотя где-то видел у тебя `getSubject`.

2020-11-16 20:36 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +  const { value, handleChange, handleSubmit } = useHelpers(setResult)
Хм, может и стейт результата вынести в твой кастомный хук?

2020-11-18 11:45 UTC, ilyasidorchik requested changes
Руслан, ты закончил эту задачу, всё правильно.

Но, пожалуйста, обработай случай, когда предмет не найден, например «китайский». Нужно просто обернуть запрос к Апи в `try/catch`, а `catch` просто залогировать ошибку.

<img width="815" alt="image" src="https://user-images.githubusercontent.com/53493445/99526510-65904700-29ac-11eb-98dc-4edbd3ddf978.png">

2020-11-19 18:53 UTC, ilyasidorchik requested changes
Эх, я думал, уже заапрувлю, но ладно.

2020-11-19 18:53 UTC, ilyasidorchik commented on src/components/Search/api.js
> +
Пустая строка.

2020-11-19 18:53 UTC, ilyasidorchik commented on src/components/Search/api.js
> +    console.log("error")
А какая ошибка? `catch (error)`

2020-11-19 18:53 UTC, ilyasidorchik commented on src/components/Search/api.js
> -  return data ? data.subject : ''
Сделай этот файл, как было. Нужно было просто обернуть запрос к Апи в `try/catch`.

2020-11-19 18:53 UTC, ilyasidorchik commented on src/components/Search/hooks/useHelpers.js
> +
?

2020-11-19 18:53 UTC, ilyasidorchik commented on src/components/Search/Result/Result.js
> +      {name === undefined ?
Можно просто `name ? ...`. Мне кажется, ты не отформатировал этот файл.

2020-11-19 18:53 UTC, ilyasidorchik commented on src/components/Search/Result/Result.scss
> +	&-Link, &-Error {
Так не делают по БЭМу. Лучше `.Result-Item`, а для ошибки — `.Result-Item_type_error`.

2020-11-20 15:04 UTC, akseonowww commented on src/components/Search/Result/Result.scss
> +	&-Link, &-Error {
Значит нужно переписать `Result-Link` на `Result-Item`?

2020-11-20 19:54 UTC, ilyasidorchik requested changes

2020-11-20 19:54 UTC, ilyasidorchik commented on src/components/Search/Result/Result.js
> +        <a className={cnResult('Link')} href={`https://${name}-ege.sdamgia.ru`}>{title}</a> :
А ты замени `Link` на `Item`, чтобы не дублировать стили в ЦССе.

2020-11-20 19:54 UTC, ilyasidorchik commented on src/components/Search/Result/Result.scss
>  		background-color: #ffecdf;
Цвета можешь вынести в модификатор `type_default`.

2020-11-20 19:54 UTC, ilyasidorchik commented on src/components/Search/Result/Result.scss
> +		&_type_error {
Можно вот так:
```scss
&_type {
  &_error {
    property: value;
  }
}
```

2020-11-20 19:54 UTC, ilyasidorchik commented on src/components/Search/api.js
>  export const getSubject = async (value) => {
Код не очень. Посмотри [эту версию своего файла](https://github.com/ilyasidorchik/sdamgia-introtask-ruslan/blob/081893ff33b62a944fd129ac0348bdb52f94b39d/src/components/Search/api.js). Обери 3—6 строки в `try`, а в `catch` прологгируй ошибку, в конце —
```js
return {
  name: '',
  title: '',
}
```
Хотя лучше `null`, если получится.

2020-11-21 16:00 UTC, ilyasidorchik requested changes
Правильнее сделать по-другому. В функции для АПИ мы возвращаем данные или инфу, что их нет, только `null`. Данные в теории могут быть с любыми полями, поэтому не стоит передавать в них пустые строки, как сейчас.

Поставь для `result` значение по умолчанию `undefined`. В компоненте `Search` добавь условие для показа уведомления: `{result !== undefined && <Result name={result.name || ''} ...}`

2020-11-21 16:00 UTC, ilyasidorchik commented on src/components/Search/api.js
> +    console.log('Error')
Нужно вывести пойманную ошибку.

2020-11-21 16:00 UTC, ilyasidorchik commented on src/components/Search/Result/Result.js
> +        <a className={cnResult('Item', { type: 'default' })} href={`https://${name}-ege.sdamgia.ru`}>{title}</a> :
Отформатировал здесь?

2020-11-21 16:18 UTC, akseonowww commented on src/components/Search/Result/Result.js
> +        <a className={cnResult('Item', { type: 'default' })} href={`https://${name}-ege.sdamgia.ru`}>{title}</a> :
Я наверное не понимаю твоё "отформорматировать". Либо это удалить (как отформатировать флешку), либо изменить что-то. Если изменить, то кроме условия я

2020-11-21 16:24 UTC, ilyasidorchik commented on src/components/Search/Result/Result.js
> +        <a className={cnResult('Item', { type: 'default' })} href={`https://${name}-ege.sdamgia.ru`}>{title}</a> :
Я про Притиер.

[Пример, где говорят про форматирование в Prettier](https://www.digitalocean.com/community/tutorials/how-to-format-code-with-prettier-in-visual-studio-code-ru)

2020-11-21 16:31 UTC, akseonowww commented on src/components/Search/Result/Result.js
> +        <a className={cnResult('Item', { type: 'default' })} href={`https://${name}-ege.sdamgia.ru`}>{title}</a> :
![image](https://user-images.githubusercontent.com/54501083/99882200-cf6c5300-2c2f-11eb-8224-a3f65bb1e7ae.png)
Это похоже на "Да, отформатировал"? `Ctrl+S` нажимал.

2020-11-21 16:35 UTC, ilyasidorchik commented on src/components/Search/Result/Result.js
> +        <a className={cnResult('Item', { type: 'default' })} href={`https://${name}-ege.sdamgia.ru`}>{title}</a> :
Да, ок.

2020-11-21 16:37 UTC, akseonowww commented on src/components/Search/Result/Result.js
> +        <a className={cnResult('Item', { type: 'default' })} href={`https://${name}-ege.sdamgia.ru`}>{title}</a> :
Ты, наверное, о последней строчке? Симантически её разделить энтером?

2020-11-21 16:40 UTC, ilyasidorchik commented on src/components/Search/Result/Result.js
> +        <a className={cnResult('Item', { type: 'default' })} href={`https://${name}-ege.sdamgia.ru`}>{title}</a> :
Это я не заметил :-) Надо тоже исправить.

Я напрягся, потому что привык к другому конфига Притиера. Оставь, как есть.

2020-11-21 17:05 UTC, akseonowww commented on src/components/Search/Result/Result.js
> +        <a className={cnResult('Item', { type: 'default' })} href={`https://${name}-ege.sdamgia.ru`}>{title}</a> :
Я понял, проблема была ещё в том, что мы проверяли `data` с объектом, а само по себе имение объекта — `true`. Значит нужно было проверять `data.subject`.
![image](https://user-images.githubusercontent.com/54501083/99882802-22480980-2c34-11eb-8af9-03034f7bfba5.png) 
![image](https://user-images.githubusercontent.com/54501083/99882923-de093900-2c34-11eb-998a-f8d2d8a609b4.png)

2020-11-21 17:18 UTC, ilyasidorchik requested changes

2020-11-21 17:18 UTC, ilyasidorchik commented on src/components/Search/api.js
> +    console.log('Такого предмета нет.')
Просто `error` :-)

2020-11-21 17:18 UTC, ilyasidorchik commented on src/components/Search/api.js
> +  return {
Надо вернуть `null`

2020-11-21 17:18 UTC, ilyasidorchik commented on src/components/Search/Result/Result.js
> +        <a className={cnResult('Item', { type: 'default' })} href={`https://${name}-ege.sdamgia.ru`}>{title}</a> :
Лучше вернуть `null`

2020-11-21 20:24 UTC, akseonowww commented on src/components/Search/api.js
> +  return {
![image](https://user-images.githubusercontent.com/54501083/99886295-6515db80-2c4c-11eb-9d45-26d4826344e7.png)
Будет ошибка. Мы же потом раскладываем `null` как объект по ключам `title` и `name`.

2020-11-21 20:26 UTC, akseonowww commented on src/components/Search/Result/Result.js
> +        <a className={cnResult('Item', { type: 'default' })} href={`https://${name}-ege.sdamgia.ru`}>{title}</a> :
`[https://github.com/ilyasidorchik/sdamgia-introtask-ruslan/pull/10#discussion_r528236082 666](https://github.com/ilyasidorchik/sdamgia-introtask-ruslan/pull/10#discussion_r528236082)`

2020-11-21 20:39 UTC, ilyasidorchik commented on src/components/Search/api.js
> +  return {
Давай тогда в `Search` компоненту `Result` передавать пропсы вот так: `title={result ? result.title : ''}`.

2020-11-22 09:49 UTC, akseonowww commented
> [Лучше вернуть `null`](https://github.com/ilyasidorchik/sdamgia-introtask-ruslan/pull/10#discussion_r528219911)
Вместо уведомления?

2020-11-22 09:51 UTC, ilyasidorchik commented
https://github.com/ilyasidorchik/sdamgia-introtask-ruslan/pull/10#discussion_r528240348

2020-11-22 11:09 UTC, akseonowww commented
Но ошибка же в 20 строчке, а мы получается не решем ЕЁ, а подстравивем Search.js под неё.
![image](https://user-images.githubusercontent.com/54501083/99902083-34758680-2ccc-11eb-80fa-f638418aaca3.png)
![image](https://user-images.githubusercontent.com/54501083/99902090-42c3a280-2ccc-11eb-94ac-b4fec84d8b30.png)

2020-11-22 11:53 UTC, ilyasidorchik commented
Показал как. Конечно, лучше сделать отдельный компонент для ошибки и стейт для факта отправки формы, но давай оставим, как есть.

Если нет вопросов, напиши. Я волью.

2020-11-22 12:40 UTC, akseonowww commented
Вопросов нет, ход работы кода я понял. 
Жаль что пришлось тебе почти всё делать :-(

2020-11-22 12:53 UTC, ilyasidorchik commented
А уберёшь `undefined` в `Search` и `useHelpers`?

2020-11-22 19:07 UTC, ilyasidorchik requested changes
Ещё чуть-чуть :-)

2020-11-22 19:07 UTC, ilyasidorchik commented on src/components/Search/hooks/useHelpers.js
> +  const [result, setResult] = useState('')
Здесь нужно `null`

2020-11-22 19:07 UTC, ilyasidorchik commented on src/components/Search/api.js
> +    console.log('error')
```suggestion
    console.log(error)
```

:-)

2020-11-22 19:12 UTC, ilyasidorchik approved these changes

2020-11-22 19:13 UTC, merged