11 training redux
ilyasidorchik/sdamgia-introtask-ruslan pull request #13
Opened 2020-12-03 09:30 UTC by akseonowww

2020-12-06 11:48 UTC, ilyasidorchik commented on src/modules/subject/duck.js
> +}
Если хочешь выводить уведомление об ошибке:

```suggestion
// Thunk - Функция для получение данных с сервера
export const fetchSubject = (value) => async (dispatch) => {
  try {
    const result = await getSubject(value)

    const newSubject = result || {
      name: '',
      title: '',
    }

    dispatch(fetchSubjectSuccess(newSubject))
  } catch (error) {
    console.log(error)
  }
}
```

2020-12-06 11:49 UTC, ilyasidorchik requested changes
В целом, всё ок. Понял концепцию Редакса, да?

2020-12-06 11:49 UTC, ilyasidorchik commented on package.json
> +    "redux-thunk": "^2.3.0"
Установи версии пакетов, которые не обновятся сами до нового патча.

2020-12-10 18:32 UTC, akseonowww commented on package.json
> +    "redux-thunk": "^2.3.0"
То есть всё должно быть как 14 строка: `"версия"`, в отличие `"^версия"`

2020-12-11 14:05 UTC, ilyasidorchik commented on package.json
> +    "redux-thunk": "^2.3.0"
Да.

Сначала вспомним `semver` — семантическое версионирование. Допустим, версия пакета — `1.2.3`. Это значит, что `1` — мажорный номер версии, `2` — минорный и `3` — патч.

Помнишь, что значит крышечка `^` в версии пакета? Она значит, что другой разработчик возьмёт проект, установит зависимости и автоматически подхватит новую версию в пределах мажорной. Например, `redux` был `4.0.5`, а станет `4.1.2`.

Если написать тильду `~`, пакет сможет обновляться только до новой патч-версии.

Бывали случаи, когда такое автоматическое обновление ломало сайты, поэтому лучше закреплять версию. Если `"redux": "4.0.5"`, то пакет подтянется только версии `4.0.5`.
<br/>
Документация. [`package.json`](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#dependencies)

2020-12-11 14:53 UTC, akseonowww commented on package.json
> +    "redux-thunk": "^2.3.0"
Похоже на `semver`?
"поиск": "2.1.5"
2 - перепиать на Angular (изменения не работают с поиском, который сейчас)
1 - добавить счётчик для показа кол-ва результатов (новая функция)
5 - сменить стили (изменения ни как не вредят коду)

2020-12-12 08:52 UTC, ilyasidorchik commented on package.json
> +    "redux-thunk": "^2.3.0"
Похоже.

Обычно обновляют мажорную версию, когда добавляют что-то большое или теряют совместимость с предыдущими версиями, минорную, когда добавляют фичу, и патч, когда исправляют баг.

2020-12-13 17:02 UTC, akseonowww commented
Да, понял.

2020-12-14 17:13 UTC, ilyasidorchik commented
Хорошо, остался завершающий шаг.

Обычно на проекте используют инструменты разработчика для Редакса. Там удобно понимать, сработал ли экшен и как изменился стор. Установи их.

Установка сводится к двум шагам:
1. Поставить расширение в браузере.
2. Переписать `compose` на `composeWithDevTools` из пакета `redux-devtools-extension`.

Все ссылки и пример кода в документации.
<br />
Документация. [Добавление Redux DevTools](https://redux.js.org/tutorials/fundamentals/part-4-store#redux-devtools)

2020-12-16 22:14 UTC, ilyasidorchik requested changes

2020-12-16 22:14 UTC, ilyasidorchik commented on src/store.js
> +import { createStore, applyMiddleware, compose } from 'redux'
Ты решил задачу, ок, но я [писал](https://github.com/ilyasidorchik/sdamgia-introtask-ruslan/pull/13#issuecomment-744583032):
> Переписать `compose` на `composeWithDevTools` из пакета `redux-devtools-extension`.

Так будет сделать лучше. Исправь, пожалуйста, и сделай скрин, как ты пользуешься вкладкой Редакса в браузере.

2020-12-17 22:32 UTC, akseonowww commented on src/store.js
> +import { createStore, applyMiddleware, compose } from 'redux'
![image](https://user-images.githubusercontent.com/54501083/102551646-e4be8b00-40d0-11eb-8bd4-73bd951cd9e9.png)

2020-12-17 22:39 UTC, ilyasidorchik requested changes

2020-12-17 22:39 UTC, ilyasidorchik commented on package.json
> +    "redux-devtools-extension": "^2.13.8",
Круто, но опять крышка ;–)

2020-12-17 22:43 UTC, ilyasidorchik approved these changes
Хорошо.

Завтра стяну ветку. Если всё ок, волью в мастер и дам следующее задание.

2020-12-19 10:29 UTC, ilyasidorchik requested changes
Открыл и встретил 2 ошибки. Исправляется за минуту:
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/53493445/102687152-23059880-41fe-11eb-95c5-255cceb5a5cf.png">
<img width="691" alt="image" src="https://user-images.githubusercontent.com/53493445/102687157-2d279700-41fe-11eb-9684-d82529976181.png">

2020-12-19 17:43 UTC, akseonowww commented
> Открыл и встретил 2 ошибки. Исправляется за минуту:
> <img alt="image" width="1375" src="https://user-images.githubusercontent.com/53493445/102687152-23059880-41fe-11eb-95c5-255cceb5a5cf.png">
> <img alt="image" width="691" src="https://user-images.githubusercontent.com/53493445/102687157-2d279700-41fe-11eb-9684-d82529976181.png">

Не понимаю. У меня другая ошибка. 
![image](https://user-images.githubusercontent.com/54501083/102695804-b230a180-423a-11eb-98a2-36e88a549978.png)

2020-12-20 10:05 UTC, ilyasidorchik commented
Сейчас разберём.

Вначале ты сделал проект доступным для девтулзов Редакса, добавив в коде `window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()`.

Потом я сказал, что ок, но лучше подключать функцией `composeWithDevTools` из специального пакета. Значит, твой предыдущий код больше не нужен.

2020-12-20 16:16 UTC, ilyasidorchik requested changes
Ок, осталось поправить одну вещь. Когда предмет не найден, не выводи ничего в футере.

2020-12-20 23:53 UTC, akseonowww commented
> Ок, осталось поправить одну вещь. Когда предмет не найден, не выводи ничего в футере.

Так ничего и не выводится. Может ты имел ввиду header?
![image](https://user-images.githubusercontent.com/54501083/102727617-a7a80200-4337-11eb-9985-2e2bbd04df83.png)

2020-12-21 13:44 UTC, ilyasidorchik requested changes
Остался 1 коммит)

2020-12-21 13:44 UTC, ilyasidorchik commented on src/components/Header/Header.js
> +        subject.title ? `Давай учи предмет «${subject.title}»` : null
Да. Но лучше проще: `(subject && subject.title) ? ...`. Вместо `null` я бы вернул пустую строку: `''`.

2020-12-21 13:44 UTC, ilyasidorchik commented
> Так ничего и не выводится. Может ты имел ввиду header?

Да, сорри. Имел в виду `header`.

2020-12-22 19:44 UTC, ilyasidorchik approved these changes

2020-12-22 19:45 UTC, merged