9 Add TypeScript
ilyasidorchik/sdamgia-introtask-ruslan pull request #16
Opened 2020-12-23 17:14 UTC by akseonowww

2020-12-24 10:49 UTC, ilyasidorchik requested changes

2020-12-24 10:49 UTC, ilyasidorchik commented on package.json
> +    "typescript": "^4.1.3"
Опять версия незакреплённая)

2020-12-24 10:49 UTC, ilyasidorchik commented on src/components/Button/Button.tsx
> +const Button = ({className, disabled, name}) => {
Да, но ещё нужно описать пропсы компонента с помощью интерфейса.

2020-12-24 12:35 UTC, akseonowww commented on package.json
> +    "typescript": "^4.1.3"
При **каждом** добавленном пакете нужно ставить фиксированную версию?

2020-12-24 12:37 UTC, ilyasidorchik commented on package.json
> +    "typescript": "^4.1.3"
Да, потому что каждый пакет в теории может сломать твой проект.

2020-12-24 12:39 UTC, ilyasidorchik commented on package.json
> +    "typescript": "^4.1.3"
И ты добавил не все пакеты из инструкции (она в конце ишью).

2020-12-24 17:12 UTC, ilyasidorchik requested changes

2020-12-24 17:12 UTC, ilyasidorchik commented on package.json
> +    "redux-devtools-extensitypon": "2.13.8",
Как будто случайно изменил пакет

2020-12-24 17:12 UTC, ilyasidorchik commented on src/components/Button/Button.tsx
> +const Button = ({ className, disabled, name }: IButtonProps) => {
Да, но давай лучше так:
```suggestion
const Button: FC<IButtonProps> = ({ className, disabled, name }) => {
```

`FC` — это сокращение от `Functional Component`.

2020-12-24 17:12 UTC, ilyasidorchik commented on src/components/Button/Button.tsx
> +const Button = ({ className, disabled, name }: IButtonProps) => {
`name` давай уберём: представим, что обработка форм будет только на клиенте.

2020-12-24 17:12 UTC, ilyasidorchik commented on src/components/Button/Button.tsx
>      <button className={className}>{name}</button>
```suggestion
    <button className={className}>{children}</button>
```

2020-12-26 15:05 UTC, akseonowww commented on package.json
> +    "redux-devtools-extensitypon": "2.13.8",
Так случилось поле скачивания всех остальных пакетов, про которые ты писал выше.

2020-12-26 15:31 UTC, ilyasidorchik requested changes
Ок, есть минорные замечания. Можешь исправить их и заодно добавить стили кнопке. Не забывай про независимость компонента (БЭМ).

2020-12-26 15:31 UTC, ilyasidorchik commented on package.json
> +    "redux-devtools-extensitypon": "2.13.8",
Обычно так не бывает, ну, тогда поправь сам, потому что написанного пакета нет:
<img width="676" alt="image" src="https://user-images.githubusercontent.com/53493445/103154348-fcb89d80-47a7-11eb-858e-9850b22e40e4.png">

2020-12-26 15:31 UTC, ilyasidorchik commented on src/components/Button/Button.tsx
> +const Button: FC<IButtonProps> = ({ className, disabled, children}) => {
Да, но как будто не отформатировал.

2020-12-26 15:31 UTC, ilyasidorchik commented on src/components/Button/Button.tsx
>    disabled: false,
То есть кнопка не может быть с пропсом `disabled` (равным `true`)?

2020-12-26 15:40 UTC, akseonowww commented on src/components/Button/Button.tsx
>    disabled: false,
Я думал даю значение по умолчанию.

2020-12-26 15:43 UTC, ilyasidorchik commented on src/components/Button/Button.tsx
>    disabled: false,
Нет, здесь, в интерфейсе или типе, ты описываешь типы пропсов: `boolean`, `string` или что-то другое.

Значения по умолчанию задаются в функции.

2020-12-28 13:17 UTC, akseonowww commented
Я нажимал Ctrl+S.

2020-12-28 13:55 UTC, ilyasidorchik requested changes
Ок, можно дальше.

2020-12-29 10:31 UTC, ilyasidorchik requested changes

2020-12-29 10:31 UTC, ilyasidorchik commented on src/components/Button/Button.tsx
> +    <button className={cx(button(), className)}>{children}</button>
Ты написал рабочий код, ок, но лучше использовать меньше библиотек. Я сам не так давно узнал об этом способе. Можно склеить классы библиотекой `@bem-react/classname`
```suggestion
    <button className={button(null, [className])}>{children}</button>
```
<br>

Пример такого [в @yandex-ui](https://github.com/bem/yandex-ui/blob/d0ac21393d6defbff5e6dcbd499de2ac7f4d5cde/src/Link/Link.tsx#L123)

2020-12-29 10:31 UTC, ilyasidorchik commented on src/components/Button/Button.tsx
> +  const button = cn('Button')
Ты всё верно написал, но я пришёл к тому, что лучше писать в стиле `cnClassName`:
```suggestion
  const cnButton = cn('Button')
```

Так не будет пересечений с обычными переменными.

2020-12-29 10:31 UTC, ilyasidorchik commented on src/components/Button/Button.tsx
> +const Button: FC<IButtonProps> = ({ className, disabled, children}) => {
Слева есть пробел, а справа нет `¯\_(ツ)_/¯ `
```suggestion
const Button: FC<IButtonProps> = ({ className, disabled, children }) => {
```

2020-12-29 10:31 UTC, ilyasidorchik commented on src/components/Button/Button.scss
> +  margin-top: 9px;
Можешь внедрить кнопку в свой проект: в форму поиска предмета. Здесь будет момент, вернёмся к нему позже.

2020-12-29 10:31 UTC, ilyasidorchik commented on src/components/Button/Button.scss
> +  background: linear-gradient(to left, to top, #d2e2ff, #9dccff);
Если хочешь, это необязательно, можешь отформатировать цсс, то есть распределить классы по группам: вставить в какой-нибудь файл в проекте Сдам ГИА и форматнуть.

2020-12-29 10:42 UTC, akseonowww commented on src/components/Button/Button.scss
> +  background: linear-gradient(to left, to top, #d2e2ff, #9dccff);
Импортировать всё в один?

2020-12-29 10:43 UTC, ilyasidorchik commented on src/components/Button/Button.scss
> +  background: linear-gradient(to left, to top, #d2e2ff, #9dccff);
Пропусти пока этот пункт.

2020-12-29 18:34 UTC, ilyasidorchik requested changes

2020-12-29 18:34 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +        <Button children="Поиск" />
```suggestion
        <Button>Найти</Button>
```

Я также поменял надпись на кнопке: обычно кнопка — глагол, а ссылка — существительное.

2020-12-29 18:34 UTC, ilyasidorchik commented on package.json
> +    "@bem-react/classnames": "1.3.9",
Добавленный пакет остался. Пакет удаляется командой `npm uninstall` или сокращённо `npm un`.

<br>

Дока НПМ. [`npm uninstall`](https://docs.npmjs.com/cli/v6/commands/npm-uninstall)

2020-12-29 18:34 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +import Button from '../Button/Button'
Если ты вынес кнопку, пора удалить стиль:
https://github.com/ilyasidorchik/sdamgia-introtask-ruslan/blob/fbd72eb2cd23a40c03749b9334b7d0d852324ea3/src/components/Search/Search.scss#L19

2021-01-02 09:28 UTC, ilyasidorchik requested changes

2021-01-02 09:28 UTC, ilyasidorchik commented on src/components/Button/Button.tsx
> +const Button: FC<IButtonProps> = ({ className, disabled, children }) => {
Не используешь `disabled`:
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/53493445/103454411-a3df8c80-4cf4-11eb-831d-e81d78634c42.png">

2021-01-04 07:26 UTC, akseonowww commented
![image](https://user-images.githubusercontent.com/54501083/103510894-18423900-4e77-11eb-9b64-a17dcd6e2836.png)
Может установить плагины и скопировать настройки с сдамгиа?

2021-01-04 08:00 UTC, ilyasidorchik commented
Думаю, для Стайллинта будет достаточно скопировать `.stylelintrc`.

2021-01-06 09:14 UTC, ilyasidorchik requested changes
👍

2021-01-06 09:14 UTC, ilyasidorchik commented on src/components/Button/Button.scss
>    background-color: #d2e2ff;
```suggestion
  background: #d2e2ff;
  background: linear-gradient(to left, to top, #d2e2ff, #9dccff);
```

2021-01-06 09:14 UTC, ilyasidorchik commented on src/components/Button/Button.tsx
> +    <button className={cnButton(null, [className])} disabled={disabled}>
Кажется, что кнопка теперь всегда неактивна.

2021-01-06 14:49 UTC, akseonowww commented on src/components/Button/Button.tsx
> +    <button className={cnButton(null, [className])} disabled={disabled}>
На 12 строке у `disabled` по умолчанию `false`.
![image](https://user-images.githubusercontent.com/54501083/103781511-863d5a80-5047-11eb-849f-83b240c12860.png)

2021-01-06 15:00 UTC, ilyasidorchik requested changes

2021-01-06 15:00 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +        <Button>Найти</Button>
Ты раньше здесь передавал `disabled`.

2021-01-06 15:05 UTC, akseonowww commented on src/components/Search/Search.js
> +        <Button>Найти</Button>
Нужно передать?

2021-01-06 15:20 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +        <Button>Найти</Button>
Да, `true`, если поле пустое. Соответственно, нужно будет написать стиль для модификатора `Button_disabled`.

2021-01-08 14:47 UTC, ilyasidorchik requested changes

2021-01-08 14:47 UTC, ilyasidorchik commented on src/components/Button/Button.scss
> +    filter: grayscale(100%);
Сильно.

2021-01-08 14:47 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +        <Button disabled={value === '' ? true : false}>Найти</Button>
Можно проще:
```suggestion
        <Button disabled={!value}>Найти</Button>
```

2021-01-09 10:50 UTC, ilyasidorchik requested changes

2021-01-09 10:50 UTC, ilyasidorchik commented on src/components/Button/Button.scss
> +  &_disabled {
Разве модификатор применяется?

https://github.com/ilyasidorchik/sdamgia-introtask-ruslan/blob/ed3688377632144086694da29caa16c554f740c5/src/components/Button/Button.tsx#L16

2021-01-10 16:21 UTC, ilyasidorchik requested changes

2021-01-10 16:21 UTC, ilyasidorchik commented on src/components/Footer/Footer.scss
>    align-items: center;
У тебя повторяется код для шапки и футера, под это можно сделать отдельный БЭМ-блок (компонент). Но пропустим это, потому что ждут боевые задачки в Сдам ГИА.

2021-01-10 16:21 UTC, ilyasidorchik commented on src/components/Button/Button.tsx
> +  <button className={cnButton({disabled: disabled}, [className])} disabled={disabled}>
Да, молодец, но лучше короче:
```suggestion
  <button className={cnButton({disabled}, [className])} disabled={disabled}>
```

2021-01-10 16:27 UTC, ilyasidorchik approved these changes

2021-01-10 16:28 UTC, merged