10 Deploy
ilyasidorchik/sdamgia-introtask-ruslan pull request #17
Opened 2021-01-11 17:15 UTC by akseonowww

2021-01-12 19:16 UTC, ilyasidorchik requested changes

2021-01-12 19:16 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
> +  it('render correctly', () => {
```suggestion
  it('renders correctly', () => {
```

2021-01-12 19:16 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
> +  const  { container } = render(<Button>Найти</Button>)
Напиши ещё, пожалуйста, один сценарий, когда кнопку используют с дополнительным классом и неактивностью.

Лучше оформить это так:
```js
describe('Button', () => {
  describe('common', () => {
    ...
  })

  describe('with extra className and disabled', () => {
    ...
  })
})
```

2021-01-12 19:16 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
> +  const  { container } = render(<Button>Найти</Button>)
Не забывай форматировать :-)
```suggestion
  const { container } = render(<Button>Найти</Button>)
```

2021-01-17 17:39 UTC, akseonowww commented on src/components/Button/Button.test.tsx
> +  const  { container } = render(<Button>Найти</Button>)
Так?
![image](https://user-images.githubusercontent.com/54501083/104851116-0e531800-5904-11eb-9924-f7c9f77e1570.png)

2021-01-17 17:52 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
> +  const  { container } = render(<Button>Найти</Button>)
Не отправляй код скриншотом, сразу пуш, исправим)

2021-01-17 17:54 UTC, akseonowww commented on src/components/Button/Button.test.tsx
> +  const  { container } = render(<Button>Найти</Button>)
Ok

2021-01-17 18:01 UTC, ilyasidorchik requested changes

2021-01-17 18:01 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
> +    const component = container.querySelector('.Button', '.Button_disabled')
```suggestion
    const component = container.querySelector('.Button.Button_disabled')
```

2021-01-17 18:01 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
>    const  { container } = render(<Button>Найти</Button>)
А где ты прокинул класс и пропс для неактивности?

2021-01-17 18:04 UTC, akseonowww commented on src/components/Button/Button.test.tsx
>    const  { container } = render(<Button>Найти</Button>)
Не понял :(

2021-01-17 18:06 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
>    const  { container } = render(<Button>Найти</Button>)
Ты протестировал компонент в минимальной комплектации. Я попросил протестировать второй сценарий: когда в компонент прокинули класс и пропс для неактивности. Где ты сделал это?

2021-01-19 18:03 UTC, ilyasidorchik requested changes

2021-01-19 18:03 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
> +    const  { container } = render(<Button className={this.className}>Найти</Button>)
Тест прошёл?

2021-01-19 18:03 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
> +    const component = container.querySelector('.Button')
```suggestion  
  describe('common', () => {
    const { container } = render(<Button>Найти</Button>)
    const component = container.querySelector('.Button')
```

2021-01-19 18:03 UTC, ilyasidorchik commented on src/components/Button/__snapshots__/Button.test.tsx.snap
> +exports[`Button with extra className and disabled matches snapshot 1`] = `null`;
`null`, а нам нужен снепшот компонента.

2021-01-25 18:31 UTC, ilyasidorchik requested changes

2021-01-25 18:31 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
> +    const  { container } = render(<Button className={this.className}>Найти</Button>)
Да. Прокинь ещё `disabled`.

2021-01-25 18:40 UTC, ilyasidorchik requested changes

2021-01-25 18:40 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
> +    const  { container } = render(<Button className={this.className} disabled={true}>Найти</Button>)
Да. Если что, для булевых можно короче:
```suggestion
    const  { container } = render(<Button className={this.className} disabled>Найти</Button>)
```

Но оставь, как есть.

2021-01-25 18:40 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
> +
Удали)
```suggestion

```

2021-01-25 21:36 UTC, ilyasidorchik requested changes
Всё ок, я написал про минорные вещи.

2021-01-25 21:36 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
> +    const component = container.querySelector('.Button')
```suggestion
  describe('common', () => {
    const  { container } = render(<Button>Найти</Button>)
    const component = container.querySelector('.Button')
```

2021-01-25 21:36 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
> +    const  { container } = render(<Button className={this.className} disabled={true}>Найти</Button>)
Отформатируй:
```suggestion
    const { container } = render(<Button className={this.className} disabled={true}>Найти</Button>)
```

2021-01-25 21:36 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
> +      expect(component).toHaveTextContent('Найти')
Переименуй для разнообразия:
```suggestion
      expect(component).toHaveTextContent('Сохранить')
```

2021-01-25 21:36 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
> +    const component = container.querySelector('.Button.Button_disabled')
```suggestion
    const component = container.querySelector('.Button.Button_disabled')
```

2021-01-26 21:35 UTC, ilyasidorchik requested changes

2021-01-26 21:35 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
> +      expect(component).toHaveTextContent('Сохранить')
А саму кнопку в тесте переименовать?

2021-01-26 21:35 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
>      const component = container.querySelector('.Button')
Лучше без отступа:
```suggestion
    const { container } = render(<Button>Найти</Button>)
    const component = container.querySelector('.Button')
```

2021-01-26 21:35 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
```suggestion
```

2021-01-26 21:35 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
>      const  { container } = render(<Button className={this.className} disabled={true}>Найти</Button>)
`this.className`? Прокинь просто строку, например `"Profile-Button"`.

2021-01-27 11:58 UTC, ilyasidorchik requested changes

2021-01-27 11:58 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
Осталось

2021-01-27 11:58 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
> +    const  { container } = render(<Button className={this.className} disabled={true}>Сохранить</Button>)
Осталась проблема с классом. Тесты не работают.
```suggestion
    const  { container } = render(<Button className={this.className} disabled={true}>Сохранить</Button>)
```

2021-01-27 19:50 UTC, ilyasidorchik requested changes

2021-01-27 19:50 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
> +    const  { container } = render(<Button className={'Profile-Button'} disabled={true}>Сохранить</Button>)
Не забывай форматировать. И строку лучше сразу:
```suggestion
    const { container } = render(
      <Button className="Profile-Button" disabled={true}>
        Сохранить
      </Button>
    );
```

2021-01-27 19:50 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
> +
Давай сверим шаблон (снапшот) компонента тоже. Больше требований не будет, вот-вот заканчиваем)

2021-01-27 20:14 UTC, ilyasidorchik requested changes
Поменяй ещё, пожалуйста, в поле плейсхолдер с `Searching...` на `Предмет`.

2021-01-29 16:43 UTC, ilyasidorchik requested changes

2021-01-29 16:43 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
> +
Не добавил

2021-01-29 16:43 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
> -    const component = container.querySelector('.Button.Button_disabled')
Почему убрал эту строку? Она здесь была нужна.

2021-01-29 16:51 UTC, akseonowww commented on src/components/Button/Button.test.tsx
> -    const component = container.querySelector('.Button.Button_disabled')
> Не добави
GitHub пишет всё ок (
![image](https://user-images.githubusercontent.com/54501083/106303412-26fbf000-626b-11eb-9025-ef33c830442a.png)

2021-01-29 16:54 UTC, akseonowww commented on src/components/Button/Button.test.tsx
> -    const component = container.querySelector('.Button.Button_disabled')
>> Почему убрал эту строку? Она здесь была нужна.

Ой, она на 32 (выше скрин есть), сейчас переделаю.

2021-01-29 16:58 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
> -    const component = container.querySelector('.Button.Button_disabled')
Да, теперь сделай проверку снепшота, как делал для базового компонента.

2021-01-29 17:16 UTC, ilyasidorchik requested changes

2021-01-29 17:16 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
> +    it('renders correctly', () => {
Здесь нужна строка для отступа.

2021-01-29 17:16 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
> +      expect(component).toMatchSnapshot()
Да, но давай в обёртке, как выше с базовой кнопкой.

2021-01-29 17:30 UTC, ilyasidorchik requested changes
Да, всё ок, но обнови снепшот. Для этого просто прогони тесты ещё раз и нажми `u`.

2021-01-29 17:32 UTC, ilyasidorchik requested changes

2021-01-29 17:32 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
> +    const  { container } = render(
Не отформатировано.

2021-01-29 17:32 UTC, ilyasidorchik commented on src/components/Button/Button.test.tsx
> +    const  { container } = render(
Ещё сам `Button` форматни.

2021-01-29 17:54 UTC, ilyasidorchik requested changes

2021-01-29 17:54 UTC, ilyasidorchik commented on src/components/Button/Button.tsx
> +		<button className={cnButton({ disabled }, [className])} disabled={disabled}>
Отступ нужен, но зачем точки с запятой? Их не было в других местах

2021-01-29 18:40 UTC, akseonowww commented on src/components/Button/Button.tsx
> +		<button className={cnButton({ disabled }, [className])} disabled={disabled}>
Так Prttier сработал, хм...

2021-01-29 18:46 UTC, ilyasidorchik commented on src/components/Button/Button.tsx
> +		<button className={cnButton({ disabled }, [className])} disabled={disabled}>
Как будто, ты зашёл с другого компа ¯\\_(ツ)_/¯ 

Добавь в файл настроек Вс-кода `settings.json`:
```
  "editor.tabSize": 2,
  "prettier.useTabs": false,
  "prettier.tabWidth": 2,
  "prettier.printWidth": 80,
  "prettier.singleQuote": true,
  "prettier.semi": false,
```

2021-01-29 20:06 UTC, ilyasidorchik approved these changes
Тесты проходят:
<img width="410" alt="image" src="https://user-images.githubusercontent.com/53493445/106322193-84516a80-6286-11eb-9ddd-4cdb9b59aae6.png">

Можешь передеплоить, если хочешь.

2021-01-29 20:07 UTC, merged