Show result in Search
ilyasidorchik/sdamgia-introtask-ruslan pull request #2
Opened 2020-10-15 16:54 UTC by rusaksenov

2020-10-15 17:05 UTC, ilyasidorchik requested changes

2020-10-15 17:05 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +      const url = `https://${name}-ege.sdamgia.ru/`
Ты одинаково назвал две переменные, это путает. Плюс лучше вынести урл в саму ссылку.

2020-10-15 17:05 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +        title: title,
В ES6 появилась краткая запись: можно сразу `title,`.

2020-10-15 17:38 UTC, rusaksenov commented on src/components/Search/Search.js
> +        title: title,
![image](https://user-images.githubusercontent.com/54501083/96166180-4bcf9000-0f26-11eb-966f-bef63c59623f.png)
А так можно?

2020-10-16 10:48 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +        title: title,
Нет, это разные сущности.

2020-10-18 16:52 UTC, ilyasidorchik requested changes

2020-10-18 16:52 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +      const link = <a href={url}>{title}</a>
Руслан, это не в стиле Реакта. Вернись к прошлому варианту, где ты хранил поисковой результат в виде объекта.

2020-10-18 16:56 UTC, rusaksenov commented
![image](https://user-images.githubusercontent.com/54501083/96374540-060c0500-117c-11eb-86f9-fd92338602b1.png)

А так в стиле реакта?

2020-10-18 18:07 UTC, ilyasidorchik requested changes

2020-10-18 18:07 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +      {result && <div><a href={result.url}>{result.title}</a></div>}
Ты здесь сделал правильно

2020-10-18 18:36 UTC, ilyasidorchik requested changes

2020-10-18 18:36 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +  const [result, setResult] = useState('')
Отдельный объект `dataLink` не нужен, у тебя есть стейт `result`.

2020-10-18 20:20 UTC, ilyasidorchik requested changes
Да, круто, но осталось немного доработать.

2020-10-18 20:20 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +  const [result, setResult] = useState('')
Первоначальное значение лучше поставить явно: `null`

2020-10-18 20:20 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +      const url = `https://${name}-ege.sdamgia.ru`
Сам адрес лучше разместить в `JSX`, в ссылке.

2020-10-18 20:20 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +        title: title,
В ES6 появилась краткая запись: можно сразу `title,`.

2020-10-19 18:14 UTC, ilyasidorchik requested changes

2020-10-19 18:14 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +        url: url
Почему нельзя сократить `url` так же, как `title`?)

2020-10-19 18:14 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +      const url = <a href={`https://${name}-ege.sdamgia.ru`}>{title}</a>
Не нужно поле `url`, тебе достаточно `name`, а урл будешь формировать в `JSX`.

2020-10-22 11:05 UTC, ilyasidorchik requested changes
У тебя разве сейчас работает поиск без перезагрузки страницы?

2020-10-22 11:05 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +  const [result, setResult] = useState('')
↑

2020-10-22 11:05 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +        url: <a href={url}>{title}</a>
Руслан, нужно разделять: в стейте простые объекты, в коде `JSX`. То есть здесь нужно хранить только `url`.

2020-10-22 11:05 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +      <form onsubmit={handleClick}>
Обращай внимание на ошибки и предупреждения в консоли.

2020-10-22 12:30 UTC, ilyasidorchik requested changes

2020-10-22 12:30 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +      <form onSubmit={handleClick}>
Красава.

2020-10-22 12:30 UTC, ilyasidorchik commented on src/components/Search/Search.js
>          <button onClick={handleClick}>Поиск</button>
Тогда этот обработчик можно убрать.

2020-10-22 12:30 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +      {result && <div>{result}</div>}
Руслан, здесь нужен код ссылки. Потому что потом я попрошу тебя сделать результат поиска отдельным компонентом.

2020-10-22 13:10 UTC, ilyasidorchik requested changes

2020-10-22 13:10 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +      {result && <div><a href={`${result.url}`}>{`${result.url}`}</a></div>}
Да, но здесь не нужны шаблонные строки.

2020-10-22 13:10 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +      setResult(url)
Мы же обсуждали: в стейте поискового результата нужно хранить объект с заголовком и кодовым названием предмета.

2020-10-22 13:36 UTC, ilyasidorchik requested changes

2020-10-22 13:36 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +        url: url
↑

2020-10-22 13:36 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +      setResult(dataLink)
Да можно сразу запихнуть объект, без отдельной переменной `dataLink`.

2020-10-22 13:36 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +      {result && <div><a href={result.url}>{result.name}</a></div>}
Класс. Но адрес пусть будет в самой ссылке, а не в стейте. Так мы сможем гибче работать со ссылкой.

2020-10-22 13:51 UTC, rusaksenov commented
Ошибка. Думаю из-за сервера

`TypeError: NetworkError when attempting to fetch resource.[Learn More]`

2020-10-22 13:55 UTC, ilyasidorchik commented
Сервер работает: https://sdamgia-homework-backend.herokuapp.com/api/search?query=матем

Покажи код.

2020-10-22 14:00 UTC, ilyasidorchik requested changes
По коду не понял, в чём ошибка с сетью. Напишу кое-что в Телеграме.

2020-10-22 14:00 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +        name: name
Ну, ё-моё :-)

2020-10-22 14:00 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +  const [result, setResult] = useState('')
`null` — лучше указать явно.

2020-10-22 15:20 UTC, ilyasidorchik requested changes

2020-10-22 15:20 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +  const handleSubmit = (event) => {
Достаточно переименовать функцию, которая есть.

2020-10-22 15:54 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +      <form onSubmit={handleChange}>
Нет. У тебя же есть функция для отправки формы.

2020-10-22 16:08 UTC, ilyasidorchik requested changes
В целом, ок. Там ещё одна старая доработка + привент-дефолт лучше в начало функции. 

Работает же приложуха?

2020-10-22 16:08 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +      <form onSubmit={handleClick}>
Лучше переименовать.

2020-10-22 16:12 UTC, rusaksenov commented
Да, всё гуд, всё работает

2020-10-22 16:16 UTC, ilyasidorchik requested changes

2020-10-22 16:16 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +        name: name
)

2020-10-23 16:25 UTC, ilyasidorchik requested changes

2020-10-23 16:25 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +      {result && <div><a href={`https://${result.name}-ege.sdamgia.ru`}>{result.title}</a></div>}
В одном файле становится много всего. Выдели, пожалуйста, поисковый результат в отдельный компонент.

2020-10-23 21:29 UTC, ilyasidorchik requested changes

2020-10-23 21:29 UTC, ilyasidorchik commented on src/components/Search/Result/Result.js
> +const Result = (props) => {
Сделай деструктуризацию параметра.

2020-10-23 21:29 UTC, ilyasidorchik commented on src/components/Search/Result/Result.js
> +const Result = (props) => {
У тебя простой компонент. Можешь сразу вернуть `JSX`.

2020-10-23 21:29 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +import Result from './Result/Result'
Лучше отделять импорты из пакетов от своих пустой строкой.

2020-10-24 13:06 UTC, ilyasidorchik requested changes

2020-10-24 13:06 UTC, ilyasidorchik commented on src/components/Search/Result/Result.js
> +const Result = ({name, title}) => <div><a href={`https://${name}-ege.sdamgia.ru`}>{title}</a></div>
Да, только отформатируй.

2020-10-24 13:06 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +import Result from './Result/Result'
.

2020-10-24 14:10 UTC, ilyasidorchik approved these changes

2020-10-24 14:13 UTC, merged