Added styles
ilyasidorchik/sdamgia-introtask-ruslan pull request #7
Opened 2020-10-27 11:43 UTC by rusaksenov

2020-10-27 14:20 UTC, ilyasidorchik requested changes
Руслан, хорошо, что ты постарался сделать по БЭМу.

Также тебе нужно добавить сами классы тегам.

2020-10-27 14:20 UTC, ilyasidorchik commented on src/components/Search/Search.css
> +	background: -webkit-linear-gradient(top, #d2e2ff, #9dccff);
Не нужно добавлять вендорные префиксы для простых случаев. За тебя это делает Пост-ЦСС, который добавлен в инструмент `Create React App`. Пример:
<img width="841" alt="image" src="https://user-images.githubusercontent.com/53493445/97313405-a0083780-1877-11eb-8ec4-6f596f22248d.png">

Документация CRA (Create React App). [Пост-цсс](https://create-react-app.dev/docs/post-processing-css/)

2020-10-29 13:27 UTC, ilyasidorchik requested changes

2020-10-29 13:27 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +    <div className="search-container">
Супер. Теперь сделай именование по БЭМу в стиле Реакта.

2020-10-30 14:26 UTC, ilyasidorchik requested changes

2020-10-30 14:26 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +    <div className="Container">
Ок. Теперь вспомни, как оптимизировать БЭМ в Реакте, как ты делал в новом проекте «Сдам ГИА».

2020-11-01 12:54 UTC, ilyasidorchik requested changes

2020-11-01 12:54 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +  const container = cn('Container')
Да, всё верно, в целом. Но обычно компонент — это один блок или элемент, поэтому лучше иметь один класс с названием, как у компонента, то есть в твоём случае `Search`.

2020-11-01 12:54 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +        <button className={form('Button')}>Поиск</button>
Здорово, что ты вспомнил.

2020-11-01 12:54 UTC, ilyasidorchik commented on src/components/Search/Result/Result.js
> +const Result = ({ name, title }) => <div className="Container-Result"><a href={`https://${name}-ege.sdamgia.ru`}>{title}</a></div>
Мне кажется, что ты не отформатировал: слишком длинная строчка.

2020-11-01 12:54 UTC, ilyasidorchik commented on src/components/Search/Result/Result.css
> +.Container-Result a {
А если в результате будет несколько ссылок, и одна другого вида: например, обычная чёрная для справки? Поэтому БЭМ советует делать селекторы по классу.

2020-11-02 16:05 UTC, ilyasidorchik requested changes
Ок. Теперь перепиши свои стили на SCSS.

2020-11-02 16:05 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +  const search = cn("Search")
Лучше называть в духе `cnSearch`, потому что переменная, как у компонента, может ещё понадобиться.

2020-11-03 14:08 UTC, ilyasidorchik requested changes
Разве у тебя применились стили на СЦССе?

Не забывай, что мы именуем коммиты [в стиле Гитхаба](https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53): глагол в императиве, то есть не `Rewrited`, а `Rewrite`.

2020-11-03 14:08 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +        const url = `https://sdamgia-homework-backend.herokuapp.com/api/cnSearch?query=${value}`
Вот это лишнее :-)

2020-11-03 14:08 UTC, ilyasidorchik commented on src/components/Search/Search.scss
> +	width: 100%;
Попробуй отформатировать стили.

2020-11-03 15:10 UTC, ruslanaksenowww commented
_Разве у тебя применились стили на СЦССе?_

Нет. У меня ещё ошибка в том, что Reac не понимет что такое `cn`

2020-11-05 17:16 UTC, ilyasidorchik requested changes
<img width="699" alt="image" src="https://user-images.githubusercontent.com/53493445/98273848-cc246680-1fa3-11eb-90c7-56dee70c6662.png">

У меня не запустилось твоё приложение. Ты перед отправкой проверяй это, пожалуйста.

2020-11-05 17:16 UTC, ilyasidorchik commented on src/components/Search/Search.scss
> +  &, &-Form {
Лучше вернуть здесь, как было. Так больше по БЭМу.

2020-11-07 14:33 UTC, ilyasidorchik requested changes
Молодец.

2020-11-07 14:33 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +import { cn } from '@bem-react/classname'
Лучше импорты из пакетов держать в месте, то есть не отбивать пустой строкой.

2020-11-07 15:29 UTC, ilyasidorchik requested changes

2020-11-07 15:29 UTC, ilyasidorchik commented on src/components/Search/Result/Result.js
> +    <div className={cnResult()}><a className={cnResult('Link')} href={`https://${name}-ege.sdamgia.ru`}>{title}</a></div>
Разве эта строка отформатирована?

2020-11-07 15:42 UTC, ruslanaksenowww commented on src/components/Search/Result/Result.js
> +    <div className={cnResult()}><a className={cnResult('Link')} href={`https://${name}-ege.sdamgia.ru`}>{title}</a></div>
Скобки убрать?

2020-11-07 15:43 UTC, ilyasidorchik commented on src/components/Search/Result/Result.js
> +    <div className={cnResult()}><a className={cnResult('Link')} href={`https://${name}-ege.sdamgia.ru`}>{title}</a></div>
Она кажется слишком длинной.

2020-11-07 16:17 UTC, ilyasidorchik approved these changes

2020-11-07 16:18 UTC, merged